---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler-plugins.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scheduler-plugins.labels" . | nindent 4 }}
{{- if .Values.controller.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scheduler-plugins.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scheduler-plugins.labels" . | nindent 4 }}
{{- end }}
